# Generated by Django 4.1 on 2022-08-25 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('type', models.CharField(choices=[('two', 'TWO WHEELER'), ('three', 'THREE WHEELER'), ('four', 'FOUR WHEELER')], default='CHOOSE', max_length=30)),
                ('vehicle_model', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
