# Generated by Django 4.1 on 2022-08-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_model',
            field=models.CharField(max_length=200),
        ),
    ]
